#!/bin/bash
# 使用lexec explorer 代替

pwd_=$(pwd)
if [ $# -eq 0 ] ; then
#    echo $pwd_ | sed -e 's/\//\\/g' | sed -e 's/\\opt\\qiyunhu/Z:/' | tee "$(dirname $0)/flag"
    target=$(echo $pwd_ | sed -e 's/\//\\/g' | sed -e 's/\\opt\\qiyunhu/Z:/')
else
#    readlink -f $1 | sed -e 's/\//\\/g' | sed -e 's/\\opt\\qiyunhu/Z:/' | tee "$(dirname $0)/flag"
    target=$(readlink -f $1 | sed -e 's/\//\\/g' | sed -e 's/\\opt\\qiyunhu/Z:/')
fi


target=$( echo $target | sed -e 's/\\/\\\\/g' )
#echo $target
qyh $PROXY_HOST  explorer $target
