#!/usr/bin/env python
# -*- coding:utf-8 -*-

def send_command( cmd ) :
    import socket , os , sys
    host = os.getenv( "PROXY_HOST" )
    port = 2334
    sock = socket.socket( )
    sock.connect( ( host , port ) ) 
    sock.send( cmd )
    recv = sock.recv( 1 )
    while recv != "" :
        sys.stdout.write( recv )
        recv = sock.recv( 1 )

if __name__ == '__main__' :
    import sys
    if len( sys.argv ) > 1 :
        send_command( ' '.join( sys.argv[1:] ) )