#!/bin/env bash

BASE=/Users/qiyunhu/Shadow/

export PROXY_HOST=localhost
PROXY_PORT=2333
export TIME_STYLE=+"%Y.%m.%d %H:%M:%S"
export HISTFILESIZE=99999999
export HISTSIZE=99999999
export HISTTIMEFORMAT="[%F %T] "
export HISTFILE=~/.zsh_history_qyh
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

function main {
    show_banner
    set_working_dir "$@"
    set_PS1
    set_proxy
    clean_proxy
    set_PATH
    stty -ixon
    jdk_home
    export LS_COLORS=`cat $BASE/tools/_LS_COLORS_`
}

function set_working_dir {
    export desktop=/Users/qiyunhu/Desktop
    # export wv=/mnt/c/Users/Ending/.qyh_vim
    export ws=/Users/qiyunhu/Shadow/Sources
    export wn=/Users/qiyunhu/Shadow/notes
    # export wp=/mnt/e/pdf
    # export wcc=/mnt/d/binary/cmder/config
}

function set_PS1 {
    # PS1="\[\e]0;\w\a\]\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ "
    # PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
}

function set_proxy {
    export http_proxy=$PROXY_HOST:$PROXY_PORT
    export https_proxy=$PROXY_HOST:$PROXY_PORT
}

function clean_proxy {
    export http_proxy=
    export https_proxy=
}


function set_PATH {
    export PATH=$PATH:$BASE/tools:/opt/metasploit-framework/bin
}

function show_banner {
    clear
    cat $BASE/tools/banner.txt
}

function jdk_home {
    
    export JAVA_6_HOME=`/usr/libexec/java_home -v "1.6*"`
    export JAVA_8_HOME=`/usr/libexec/java_home -v "1.8*"`
    export JAVA_9_HOME=`/usr/libexec/java_home -v "9*"`
    
    export JAVA_HOME=$JAVA_8_HOME
    
    alias jdk6="export JAVA_HOME=$JAVA_6_HOME"
    alias jdk8="export JAVA_HOME=$JAVA_8_HOME"
    alias jdk9="export JAVA_HOME=$JAVA_9_HOME"

}

main "$@"





# alias ls="ls -h -F --color=auto --show-control-chars"
# alias ll="ls -h -F -l --color=auto --show-control-chars"
# alias du="du -h --time --max-depth=1"
# alias gl="git log --oneline --all --graph --decorate"
# alias gt="git status --short --branch"
