#!/bin/env bash

BASE=/root
rcfile=$BASE/.qyh_vim/vimrc
export PROXY_HOST=192.168.3.152
PROXY_PORT=2333

main( ) {
    set_PS1
    set_proxy
    clean_proxy
    set_PATH
    show_banner
    stty -ixon
}

set_PS1( ) {
    PS1="\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ "
}

vim_( ) {
    vim -u "$rcfile" $*
}

set_proxy( ) {
    export http_proxy=$PROXY_HOST:$PROXY_PORT
    export https_proxy=$PROXY_HOST:$PROXY_PORT
}

clean_proxy( ) {
    export http_proxy=
    export https_proxy=
}

set_PATH( ) {
    export PATH=$PATH:$BASE/tools
}

show_banner( ) {
    clear
    cat $BASE/tools/banner.txt
}

main "$@"