#!/bin/env bash

BASE=/home/Administrator
rcfile=/cygdrive/c/Users/Administrator.AXX3DX8ZNMSGU5B/.qyh_vim/vimrc
export PROXY_HOST=192.168.3.152
PROXY_PORT=2333

main( ) {
    set_working_dir "$@"
    set_PS1
    set_proxy
    clean_proxy
    set_PATH
    show_banner
    stty -ixon
    source /etc/bash_completion.d/git
}

set_working_dir( ) {
    export desktop=/cygdrive/c/Users/Administrator.AXX3DX8ZNMSGU5B/Desktop
}

set_PS1( ) {
    PS1="\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ "
}

set_proxy( ) {
    export http_proxy=$PROXY_HOST:$PROXY_PORT
    export https_proxy=$PROXY_HOST:$PROXY_PORT
}

clean_proxy( ) {
    export http_proxy=
    export https_proxy=
}


set_PATH( ) {
    export PATH=$PATH:$BASE/tools
}

show_banner( ) {
    clear
    cat $BASE/tools/banner.txt
}

vim_( ) {
    vim -u "$rcfile" $*
}

ls( ){
    ls.exe -N -F --color=auto --show-control-chars $*
}

ll( ){
    ls.exe -N -lF --color=auto --show-control-chars $*
}

git( ){
    /usr/bin/git.exe $*
}

main "$@"